name: ci

on:
  push:
    branches:
      - 'build'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-frontend

      - name: Run script to change files, build docker and push to ECR
        run: |
          build/workflow.sh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
          ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
